# Generated by Django 5.0.2 on 2024-02-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_remove_message_id_message_pk_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pk_number',
        ),
        migrations.AddField(
            model_name='message',
            name='id_number',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
    ]
