# Generated by Django 5.0.2 on 2024-02-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0004_remove_message_id_number_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AddField(
            model_name='message',
            name='id_number',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
