# Generated by Django 5.0.2 on 2024-02-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0005_remove_message_id_message_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id_number',
        ),
        migrations.AddField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
